name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  upload-wally:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ffrostfall/fluid

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.0

      - name: Log into Wally
        run: wally login --token "${{ secrets.WALLY_SECRET }}"

      - name: Upload to Wally
        run: wally publish

  upload-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ffrostfall/fluid

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.0

      - name: Build rbxm
        run: rojo build default.project.json -o build.rbxm

      - name: Release
        run: gh release upload ${{github.event.release.tag_name}} build.rbxm
